"""Cargar provincias datar

Revision ID: 0573ee65b801
Revises: 302a440d34e6
Create Date: 2017-07-11 12:55:51.991421

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0573ee65b801'
down_revision = '302a440d34e6'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_csv', 'provincias.csv')
    res = conn.execute(
        sa.text("COPY datar_provincias (id, nombre) FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
