"""Create Datar Alturas

Revision ID: 1da9d82b6b88
Revises: ebd91a311862
Create Date: 2017-07-16 16:21:54.429507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da9d82b6b88'
down_revision = 'ebd91a311862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_alturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_calle', sa.Integer(), nullable=True),
    sa.Column('desde', sa.Integer(), nullable=True),
    sa.Column('hasta', sa.Integer(), nullable=True),
    sa.Column('id_cpa', sa.Integer(), nullable=True),
    sa.Column('id_cp_1974', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_alturas')
    # ### end Alembic commands ###
