"""Quitar alturas.codpostal

Revision ID: 21fa0d61b52a
Revises: 23e09e1548f8
Create Date: 2017-07-09 22:57:42.334198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fa0d61b52a'
down_revision = '23e09e1548f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alturas', 'codpostal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alturas', sa.Column('codpostal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
