"""Create datar cp_1974 y tipos_camino

Revision ID: 2c32ae704ce2
Revises: 3afa97c67068
Create Date: 2017-07-16 16:40:19.937677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c32ae704ce2'
down_revision = '3afa97c67068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_cp_1974',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_postal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datar_tipos_camino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_tipos_camino')
    op.drop_table('datar_cp_1974')
    # ### end Alembic commands ###
