"""Create datar cpa

Revision ID: 358585951860
Revises: 634382ee3883
Create Date: 2017-07-11 13:14:55.664769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358585951860'
down_revision = '634382ee3883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_cpa',
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('cpa', sa.Text(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('temp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_cpa')
    # ### end Alembic commands ###
