"""LoadDatar Alturas

Revision ID: 3afa97c67068
Revises: 1da9d82b6b88
Create Date: 2017-07-16 16:22:15.886622

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afa97c67068'
down_revision = '1da9d82b6b88'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_csv', 'alturas.csv')
    res = conn.execute(
        sa.text("COPY datar_alturas (id,id_calle,desde,hasta,id_cpa,id_cp_1974) "
                "FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
