"""Load datar cp_1974 y tipos_camino

Revision ID: 3fb2c9754bc3
Revises: 2c32ae704ce2
Create Date: 2017-07-16 16:40:41.725787

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb2c9754bc3'
down_revision = '2c32ae704ce2'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_csv', 'cp_1974.csv')
    res = conn.execute(
        sa.text("COPY datar_cp_1974 (id, cod_postal) "
                "FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )
    path = os.path.join(cwd, 'cpa_csv', 'tipos_camino.csv')
    res = conn.execute(
        sa.text("COPY datar_tipos_camino (id, nombre) "
                "FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
