"""localidad.codprov foreign key

Revision ID: 43b0cbee6f27
Revises: fd368cf80282
Create Date: 2017-07-09 23:07:32.355542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b0cbee6f27'
down_revision = 'fd368cf80282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
