"""Crear datar localidades

Revision ID: 5f9f709b0502
Revises: 7308af5c486f
Create Date: 2017-07-11 13:00:58.835060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9f709b0502'
down_revision = '7308af5c486f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paraje', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('id_cpa', sa.Integer(), nullable=True),
    sa.Column('id_cp_1974', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_localidades')
    # ### end Alembic commands ###
