"""Agregar localidad.cp, codprov manzana

Revision ID: 78a7c623d43d
Revises: bba8b46c8b60
Create Date: 2017-07-09 22:31:14.308317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a7c623d43d'
down_revision = 'bba8b46c8b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidad', sa.Column('codprov', sa.String(length=1), nullable=True))
    op.add_column('localidad', sa.Column('cp', sa.Integer(), nullable=True))
    op.add_column('localidad', sa.Column('manzana', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('localidad', 'manzana')
    op.drop_column('localidad', 'cp')
    op.drop_column('localidad', 'codprov')
    # ### end Alembic commands ###
