"""Agrega alturas.manzana

Revision ID: 7d4641b59548
Revises: 8d55f450e158
Create Date: 2017-07-09 21:50:22.868890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4641b59548'
down_revision = '8d55f450e158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alturas', sa.Column('manzana', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alturas', 'manzana')
    # ### end Alembic commands ###
