"""mas constraints

Revision ID: 8e7f86013f16
Revises: d143b35fcad3
Create Date: 2017-07-09 23:10:11.892737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7f86013f16'
down_revision = 'd143b35fcad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alturas', 'provincias', ['codprov'], ['codprov'])
    op.create_unique_constraint(None, 'localidad', ['codloc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'localidad', type_='unique')
    op.drop_constraint(None, 'alturas', type_='foreignkey')
    # ### end Alembic commands ###
