"""Initial

Revision ID: 9892368e657f
Revises: 
Create Date: 2017-07-09 00:28:06.901146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9892368e657f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codcalle', sa.Integer(), nullable=True),
    sa.Column('desde', sa.Integer(), nullable=True),
    sa.Column('hasta', sa.Integer(), nullable=True),
    sa.Column('codpostal', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codcalle', sa.Integer(), nullable=True),
    sa.Column('tipocalle', sa.String(length=50), nullable=True),
    sa.Column('nombrecalle', sa.String(length=50), nullable=True),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('nombrealt', sa.String(length=50), nullable=True),
    sa.Column('codloc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codloc', sa.Integer(), nullable=True),
    sa.Column('localidad', sa.String(length=50), nullable=True),
    sa.Column('codpostal', sa.String(length=50), nullable=True),
    sa.Column('partido', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('codpart', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codpart', sa.Integer(), nullable=True),
    sa.Column('partido', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codprov', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provincias')
    op.drop_table('partidos')
    op.drop_table('localidad')
    op.drop_table('calles')
    op.drop_table('alturas')
    # ### end Alembic commands ###
