"""Initial

Revision ID: ade58fabb839
Revises: 
Create Date: 2017-07-06 00:02:30.269854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade58fabb839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    res = connection.execute("""COPY localidad FROM '/tmp/cpa_argentina/localidad.CSV' DELIMITER ';' HEADER CSV;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
