"""Link provincias a datar_provincias

Revision ID: b2fb162d4f77
Revises: 13b0071772d4
Create Date: 2017-07-16 17:27:11.567105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fb162d4f77'
down_revision = '13b0071772d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincias', sa.Column('id_datar_provincias', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    conn = op.get_bind()
    res = conn.execute(
        sa.text("UPDATE provincias p SET id_datar_provincias = dp.id "
                "FROM datar_provincias dp WHERE dp.nombre = p.provincia;"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provincias', 'id_datar_provincias')
    # ### end Alembic commands ###
