"""Partido unico

Revision ID: b87723ea7490
Revises: c49a1e1767b7
Create Date: 2017-07-09 23:01:09.687960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87723ea7490'
down_revision = 'c49a1e1767b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'partidos', ['codpart'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidos', type_='unique')
    # ### end Alembic commands ###
