"""Carga localidad

Revision ID: b9f10d6796b0
Revises: bb2057fb6686
Create Date: 2017-07-09 00:32:14.365859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f10d6796b0'
down_revision = 'bb2057fb6686'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    res = conn.execute("""COPY localidad (codloc, localidad, codpostal, partido, provincia, codpart) FROM"""
        """'/tmp/cpa_argentina/localidad.CSV' DELIMITER ';' HEADER CSV;""")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
