"""Carga partidos

Revision ID: bb2057fb6686
Revises: c7852270aba9
Create Date: 2017-07-09 00:30:55.733455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2057fb6686'
down_revision = 'c7852270aba9'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    res = conn.execute("""COPY partidos (codpart, partido, provincia) FROM"""
        """'/tmp/cpa_argentina/partidos.CSV' DELIMITER ';' HEADER CSV;""")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
