"""Quitar localidad.partido

Revision ID: bba8b46c8b60
Revises: 47430f36deec
Create Date: 2017-07-09 22:29:18.131187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba8b46c8b60'
down_revision = '47430f36deec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('localidad', 'partido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localidad', sa.Column('partido', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
