"""Carga calles

Revision ID: bdf65a23680c
Revises: b9f10d6796b0
Create Date: 2017-07-09 00:33:39.306211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf65a23680c'
down_revision = 'b9f10d6796b0'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    res = conn.execute("""COPY calles (codcalle, tipocalle, nombrecalle, barrio, referencia, nombrealt, codloc) FROM"""
        """'/tmp/cpa_argentina/calles.CSV' DELIMITER ';' HEADER CSV;""")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
