"""Provincia unica

Revision ID: c49a1e1767b7
Revises: 21fa0d61b52a
Create Date: 2017-07-09 23:00:17.183793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49a1e1767b7'
down_revision = '21fa0d61b52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'provincias', ['codprov'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provincias', type_='unique')
    # ### end Alembic commands ###
