"""Carga

Revision ID: c7852270aba9
Revises: 9892368e657f
Create Date: 2017-07-09 00:28:34.797885

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7852270aba9'
down_revision = '9892368e657f'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_argentina', 'provincias.CSV')
    res = conn.execute(
        sa.text("COPY provincias (codprov, provincia) FROM :path DELIMITER ';' HEADER CSV;"),
        path=path
    )

    path = os.path.join(cwd, 'cpa_argentina', 'partidos.CSV')
    res = conn.execute(
        sa.text("COPY partidos (codpart, partido, provincia) FROM :path DELIMITER ';' HEADER CSV;"),
        path=path
    )

    path = os.path.join(cwd, 'cpa_argentina', 'localidad.CSV')
    res = conn.execute(
        sa.text("COPY localidad (codloc, localidad, codpostal, partido, provincia, codpart) FROM :path DELIMITER ';' HEADER CSV;"),
        path=path
    )

    path = os.path.join(cwd, 'cpa_argentina', 'calles.CSV')
    res = conn.execute(
        sa.text("COPY calles (codcalle, tipocalle, nombrecalle, barrio, referencia, nombrealt, codloc) FROM :path DELIMITER ';' HEADER CSV;"),
        path=path
    )

    path = os.path.join(cwd, 'cpa_argentina', 'alturas.CSV')
    res = conn.execute(
        sa.text("COPY alturas (codcalle, desde, hasta, codpostal) FROM :path DELIMITER ';' HEADER CSV;"),
        path=path
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
