"""Carga

Revision ID: c7852270aba9
Revises: 9892368e657f
Create Date: 2017-07-09 00:28:34.797885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7852270aba9'
down_revision = '9892368e657f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    res = conn.execute("""COPY provincias (codprov, provincia) FROM"""
        """'/tmp/cpa_argentina/provincias.CSV' DELIMITER ';' HEADER CSV;""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
