"""Agregar columnas datar_cpa separado

Revision ID: cc677c8f251d
Revises: ffd4d3a9ebc9
Create Date: 2017-07-11 22:11:41.987859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc677c8f251d'
down_revision = 'ffd4d3a9ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datar_cpa', sa.Column('cp', sa.Integer(), nullable=True))
    op.add_column('datar_cpa', sa.Column('manzana', sa.String(length=3), nullable=True))
    op.add_column('datar_cpa', sa.Column('provincia', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datar_cpa', 'provincia')
    op.drop_column('datar_cpa', 'manzana')
    op.drop_column('datar_cpa', 'cp')
    # ### end Alembic commands ###
