"""localidad.codprov foreign key

Revision ID: d143b35fcad3
Revises: 43b0cbee6f27
Create Date: 2017-07-09 23:08:19.793265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd143b35fcad3'
down_revision = '43b0cbee6f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'localidad', 'partidos', ['codpart'], ['codpart'])
    op.create_foreign_key(None, 'localidad', 'provincias', ['codprov'], ['codprov'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'localidad', type_='foreignkey')
    op.drop_constraint(None, 'localidad', type_='foreignkey')
    # ### end Alembic commands ###
