"""Popular datar_cpa separado

Revision ID: d4b710947e0f
Revises: cc677c8f251d
Create Date: 2017-07-11 22:12:07.830941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b710947e0f'
down_revision = 'cc677c8f251d'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute("""UPDATE datar_cpa SET manzana=substring(cpa, 6, 8), 
        provincia=substring(cpa, 1, 1), cp=substring(cpa, 2, 4)::integer""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
