"""Crear datar parajes

Revision ID: d856dd59fc5a
Revises: 0573ee65b801
Create Date: 2017-07-11 12:58:04.085003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd856dd59fc5a'
down_revision = '0573ee65b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_parajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_parajes')
    # ### end Alembic commands ###
