"""Create DatarCalles

Revision ID: e3f182750c8f
Revises: d4b710947e0f
Create Date: 2017-07-16 16:15:31.591824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f182750c8f'
down_revision = 'd4b710947e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datar_calles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('nombre_completo', sa.Text(), nullable=True),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('nombre_abreviado', sa.Text(), nullable=True),
    sa.Column('barrio', sa.Text(), nullable=True),
    sa.Column('punto_cardinal', sa.Text(), nullable=True),
    sa.Column('id_tipo_camino', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datar_calles')
    # ### end Alembic commands ###
