"""Load DatarCalles

Revision ID: ebd91a311862
Revises: e3f182750c8f
Create Date: 2017-07-16 16:16:38.053130

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd91a311862'
down_revision = 'e3f182750c8f'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_csv', 'calles.csv')
    res = conn.execute(
        sa.text("COPY datar_calles (id, id_localidad, nombre_completo, apellido, nombre, titulo, nombre_abreviado,"
            "barrio, punto_cardinal, id_tipo_camino) FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
