"""Agrega alturas.codprov y alturas.cp

Revision ID: f5195fe91e09
Revises: fccbcd8362d7
Create Date: 2017-07-09 22:01:51.280360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5195fe91e09'
down_revision = 'fccbcd8362d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alturas', sa.Column('codprov', sa.String(length=1), nullable=True))
    op.add_column('alturas', sa.Column('cp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alturas', 'cp')
    op.drop_column('alturas', 'codprov')
    # ### end Alembic commands ###
