"""partido.codprov foreign key

Revision ID: fd368cf80282
Revises: 7f614e6d8fef
Create Date: 2017-07-09 23:06:40.776112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd368cf80282'
down_revision = '7f614e6d8fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'partidos', 'provincias', ['codprov'], ['codprov'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partidos', type_='foreignkey')
    # ### end Alembic commands ###
