"""Load datar cpa

Revision ID: ffd4d3a9ebc9
Revises: 358585951860
Create Date: 2017-07-11 13:15:09.406901

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd4d3a9ebc9'
down_revision = '358585951860'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    cwd = os.getcwd()
    path = os.path.join(cwd, 'cpa_csv', 'cpa_geo_parcial.csv')
    res = conn.execute(
        sa.text("COPY datar_cpa (id, cpa, lon, lat) FROM :path DELIMITER ',' HEADER CSV;"),
        path=path
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
